name: Docker build & push

on:
  push:
    branches: main

  workflow_dispatch:

jobs:
  docker:
    runs-on: ubuntu-latest
    
    steps:
      - name: docker build
        run: docker build . -t ${{ github.repository }}